// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkeusqnjtboksvojbtwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZXVzcW5qdGJva3N2b2pidHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjA1NzYsImV4cCI6MjA1OTg5NjU3Nn0.v2jWmOy4FZcHRSYI_ygdIkPozZhoaMenpnbf8DB-p9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);